### ISSUE TITLE
Exception thrown when YAML string does not terminate with a newline

### ISSUE THREAD

**Issue by jeffwatkins** [tj/js-yaml#13]
```
var Yaml= require('yaml');
Yaml.eval('port:3000\nserver: foo')
```

Will throw the following exception:

```
TypeError: Cannot read property '1' of undefined
    at Parser.expect (node_modules/.npm/yaml/0.1.1/package/lib/yaml.js:173:51)
    at Parser.parseHash (node_modules/.npm/yaml/0.1.1/package/lib/yaml.js:268:10)
    at Parser.parse (node_modules/.npm/yaml/0.1.1/package/lib/yaml.js:233:19)
    at Parser.parseHash (node_modules/.npm/yaml/0.1.1/package/lib/yaml.js:274:23)
    at Parser.parse (node_modules/.npm/yaml/0.1.1/package/lib/yaml.js:233:19)
    at Object.eval (node_modules/.npm/yaml/0.1.1/package/lib/yaml.js:349:46)
    at [object Context]:1:6
    at Interface.<anonymous> (repl:96:19)
    at Interface.emit (events:31:17)
    at Interface._ttyWrite (readline:309:12)
```

**Comment by zorji** [comment]
+1
