### ISSUE TITLE
Error: document not properly dedented

### ISSUE THREAD

**Issue by 4poc** [tj/js-yaml#52]
I tried to parse [this document](https://github.com/4poc/anpaste/blob/25d4f87fd0bcc09f46204ccbb96eedd465822f20/config.yaml.sample). Its a valid yaml file, I now use the libyaml bindings for this but it would be cool if this js parser would work as well.

```
> node -e "console.log(require('yaml').eval(require('fs').readFileSync('./config.yaml.sample').toString()))"

/home/apoc/projects/js/anpaste/node_modules/yaml/lib/yaml.js:179
  throw new Error(msg + ', ' + context(this.peek()[1].input))
        ^
Error: document not properly dedented, near "\nserver:\n  domain: localh"
    at Parser.expect (/home/apoc/projects/js/anpaste/node_modules/yaml/lib/yaml.js:179:9)
    at Parser.parseDoc (/home/apoc/projects/js/anpaste/node_modules/yaml/lib/yaml.js:266:8)
    at Parser.parse (/home/apoc/projects/js/anpaste/node_modules/yaml/lib/yaml.js:232:19)
    at Object.exports.eval (/home/apoc/projects/js/anpaste/node_modules/yaml/lib/yaml.js:384:46)
    at [eval]:1:29
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:901:3
```

**Comment by sandaemc** [comment]
This module is forgotten. :-(

**Comment by climaa** [comment]
The same think.
